# curl -X POST 'https://mlsgbydqugfkqygffjhz.supabase.co/rest/v1/hero_builds'
#        -H "apikey: SUPABASE_CLIENT_ANON_KEY"
#        -H "Authorization: Bearer SUPABASE_CLIENT_ANON_KEY"
#        -H "Content-Type: application/json"
#        -H "Prefer: return=minimal"
#        -d '{ "title": "description", "description": "description", "title": "photo_id" }'
###


###

POST https://mlsgbydqugfkqygffjhz.supabase.co/rest/v1/hero_builds
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sc2dieWRxdWdma3F5Z2Zmamh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjE5NTcsImV4cCI6MjA1Mjc5Nzk1N30.DWjkYTvZi70ePp0RI7QF9d5EE9nCfHNtxhYD1z0a4qs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sc2dieWRxdWdma3F5Z2Zmamh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjE5NTcsImV4cCI6MjA1Mjc5Nzk1N30.DWjkYTvZi70ePp0RI7QF9d5EE9nCfHNtxhYD1z0a4qs
Prefer: return=minimal
Content-Type: application/json

{
  "description": "as;dlmaslkdm",
  "photo_id": "AgACAgIAAxkBAAICn2eU5MT9mJ84VvwrRZqNZSPYOYhqAALz6DEbuZKpSJMyAajr4bgsAQADAgADeQADNgQ",
  "title": "asdasdasdasd"
}